### ISSUE TITLE
[vscode] Unable to access keychain (macOS)

### ISSUE THREAD

**Issue by yaoworld** [vsls-contrib/chat#277] opened 2018-12-15 08:17 UTC
Error: The user name or passphrase you entered is not correct.

- Extension Version: 0.8.2
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.30.0

**Comment by arjun27** [comment] 2018-12-15 08:18
thanks for reporting this @yaoworld. This typically happens when the system throws a keychain access prompt and the password entered is incorrect. We use the system keychain to store slack/discord tokens.

Did you see any keychain prompt?

**Comment by temitope** [comment] 2018-12-26 21:33
same behavior in my experience

**Comment by tibotiber** [comment] 2019-01-03 01:03
Same here, been having this for a while now.
```
Error: Account is required.

- Extension Version: 0.9.1
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.30.1
```

**Comment by arjun27** [comment] 2019-01-03 06:18
@tibotiber, @temitope, @yaoworld - thank you for reporting this, and apologies for the delayed response.

Interestingly the error string is different in your errors, so I'm not entirely sure if they are related. I'm investigating this and will get back to you by end of this week.

**Comment by tibotiber** [comment] 2019-01-04 06:05
@arjun27 iirc i tried to login to slack after installing and i was out of free apps so i did not succeed. Afterwards i've been having this issue each time i start vs code.

**Comment by arjun27** [comment] 2019-01-04 06:21
ah, interesting. when v0.9.0 was released, we made some changes to the local state. I think I made a mistake in the migration script to handle such cases, which would have led to this error. I have released a fix for this in v0.9.2, and it should be auto-updated for you soon.

if you have some time, it would help to know what your local state looks like. to do this, you can:

- open the command palette, and pick "Toggle Developer Tools"
- this would open the dev tools console
- run `JSON.parse(window.localStorage.getItem('storage://global/karigari.chat'))` in the dev tools console

**Comment by tibotiber** [comment] 2019-01-05 04:41
Here you go:
```
{
  "userInfo": {
    "token": "...",
    "id": "U6EH78KJS",
    "name": "thibaut",
    "teamId": "T02538B8K",
    "teamName": "Innovation"
  },
  "users": {...},
  "channels": [...],
  "lastChannel": null,
  "lastChannelId": {
    "0": "C",
    "1": "7",
    "2": "M",
    "3": "K",
    "4": "Z",
    "5": "B",
    "6": "Y",
    "7": "6",
    "8": "L",
    "vsls": "vsls-channel-id"
  },
  "extensionVersion": "0.9.1",
  "installationId": "7102137d-149e-4301-888d-6631bac5bae6"
}
```

Looking at the state, I realize this is logged in to an old slack workspace I'm not part of anymore. Not sure if that would add to the issue at hand.

**Comment by tibotiber** [comment] 2019-01-05 04:47
I can confirm the update fixed the issue. Just in case, this is the state after update.
```
{
  "userInfo": {
    "token": "...",
    "id": "U6EH78KJS",
    "name": "thibaut",
    "teamId": "T02538B8K",
    "teamName": "Innovation"
  },
  "users": {...},
  "channels": [...],
  "lastChannel": null,
  "lastChannelId": {
    "0": "C",
    "1": "7",
    "2": "M",
    "3": "K",
    "4": "Z",
    "5": "B",
    "6": "Y",
    "7": "6",
    "8": "L",
    "vsls": "vsls-channel-id"
  },
  "extensionVersion": "0.9.2",
  "installationId": "7102137d-149e-4301-888d-6631bac5bae6"
}
```

**Comment by arjun27** [comment] 2019-01-05 04:56
thanks @tibotiber. this helps a lot. here's what happened:

- the migration failed when the extension was upgraded to 0.9.0 (this needs to be fixed)
- if the local state is not reliable, the extension overwrites it by downloading updated state from the slack APIs
- but because the token is now invalid (since you've left the team), the API calls were probably failing, and the local state was never fixed.

I've created a new issue (#288) to handle such cases. thanks for your help!

**Comment by tibotiber** [comment] 2019-01-05 05:00
Thanks for breaking it down @arjun27. Sorry for wrongly appending to this issue 😬 and feel free to ping me on the new issue if I can be of any help.

**Comment by arjun27** [comment] 2019-08-05 03:14
Follow #325 for fix. Closing as duplicate

**Closed by arjun27** 2019-08-05 03:14 UTC
Labels: backlog, bug
