### ISSUE TITLE
Extension updating Slack status to away throughout the day

### ISSUE THREAD

**Issue by aejay-rs** [vsls-contrib/chat#379] opened 2019-05-15 17:24 UTC
For the past few months, my team has been battling an issue where Slack randomly (and quite frequently) marks us as away/inactive, even while we are using our machines. We find ourselves having to manually set ourselves to available in the Slack UI multiple times a day. We thought it was a bug with a recent update of Slack, but after some back and forth with their support folks, they informed us that this extension can cause the issue we are seeing.

Showing whether people are active on slack is great, but we use the normal slack app and rely on its presence-detection, so if this app is trying to update our status for us (irrespective of the presence Slack is already tracking in its own app), that eliminates this as an option for us. At least for now. It just causes too much confusion.

Let me know what other information we can gather to help troubleshoot this.

**Comment by arjun27** [comment] 2019-05-15 18:44
Thanks for reporting @aejay-rs. I want to get to the bottom of this and fix it. The extension is not expected to change the presence status on its own - only running the "Change presence status" command explicitly is expected to change it. I can review the code to ensure this behavior.

From your experience, does it look like the presence is changing in the background, without any user action?

**Comment by seantimm** [comment] 2019-05-15 18:55
I had the same problem and have disabled this extension for now.

**Comment by aejay-rs** [comment] 2019-05-16 12:53
Yeah--I had never called that command outright. I didn't realize it was even an available command until I was peeking around the source code a bit yesterday. I also got the impression that presence was only intended to be updated via that command, but I didn't know if perhaps I was just overlooking something, since I'm not very familiar with building VS Code extensions.

It's still early to be definite, but yesterday morning I disabled the extension and revoked the authorization in Slack for my own account, and I haven't seen the issue occur since then. I'm led to believe that this extension is involved but I'm not sure how or why just yet.

**Comment by arjun27** [comment] 2019-05-16 14:51
Thanks! The presence API docs talk about an "automatic away" [feature](https://api.slack.com/docs/presence-and-status#user-presence), which might be causing this issue. I'll investigate on how it "detects activity in the client".

> The Slack message servers will automatically detect activity in the client. After 30 minutes with no activity, the user is automatically marked as away. There is some additional nuance to that dependent on the client, explained in detail in our Help Center.

**Comment by btsheehy** [comment] 2019-05-17 16:51
For the record, I've been emailing Slack support about this issue for a few months, and today they told me it was likely due to this extension and advised me to revoke its permissions. 


> Hi Brandon,
> 
> Thank you for the follow up and sincerely apologize for the month-long wait while we continued to look into this. In our investigation, we found a pattern of this bug for workspaces that had the following 3rd party app. Team Chat for VS Code.
> 
> You'd need to disable your specific authentication to the app:
> 
> Go to: https://my.slack.com/apps/manage
> Look for "Team Chat for VC Code" in the list of apps and click on it to open the configuration > remove it and restart your Slack session.
> You should always now see the green circle for "Active" status in Slack.
> 
> If you could give this a shot, do let us know if it helps.
> 
> Thanks again for being patient.
>

**Comment by arjun27** [comment] 2019-05-22 21:57
fyi - I've verified that the `users.setPresence` API call is not being made from our code, unless there's an explicit user action. I'm on an email thread with the Slack developer support team to figure out how "automatic away" works and whether we can turn that off. My theory is that the RTM connection is idle, causing the "automatic away" to get triggered

**Comment by aejay-rs** [comment] 2019-05-24 13:41
Huh, yeah, that would be unexpected. If it turns out that's how the auto-away functions, they should really consider updating their API docs to make that clear. I'm sure this wouldn't be the first implementation to trip up on that.

**Comment by The-New-Guy** [comment] 2019-06-07 18:01
I am having this issue as well and can confirm it is related to this extension. Additionally, when I find I have been marked as away again despite being quite active (including carrying on conversations in the Slack app with the status still set to away). When I open up slack channel in VS Code using this extension my status is immediately set back to available.

**Comment by arjun27** [comment] 2019-06-07 18:53
Thanks for reporting this @The-New-Guy. Quick status update: the Slack support team is running tests to check if automatic away is behaving correctly. Once they share results, I will make any relevant changes at my end.

I'm eager to fix this - thanks for the patience!

**Comment by arjun27** [comment] 2019-06-20 04:59
@The-New-Guy @aejay-rs @seantimm - I have released 0.15.5 which attempts to fix this issue. From the issue reported in #395 I was able to find a potential issue that could be caused due to presence changes through the Live Share integration. Could you check if this fixes it for you?

**Comment by The-New-Guy** [comment] 2019-07-22 17:13
@arjun27 I don't really have a way to forcibly reproduce the error as it merely happened after some amount of time with VS Code open and I hadn't used VS Code in any way during that time. However, I have had VS Code open and untouched for a few hours now and my status in Slack appears to be working as I would expect.

**Comment by arjun27** [comment] 2019-08-05 03:17
Thanks, marking this as resolved

**Closed by arjun27** 2019-08-05 03:17 UTC
Labels: backlog
